image: node:10.6.0
stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build site:
  stage: build
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - npm install --progress=false
    - npm run build
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - ssh -p22 root@111.230.224.164 "mkdir htdocs/wp-content/themes/_tmp"
    - scp -P22 -r dist/* root@111.230.224.164:htdocs/wp-content/themes/_tmp
    - ssh -p22 root@111.230.224.164 "mv htdocs/wp-content/themes/live htdocs/wp-content/themes/_old && mv htdocs/wp-content/themes/_tmp htdocs/wp-content/themes/live"
    - ssh -p22 root@111.230.224.164 "rm -rf htdocs/wp-content/themes/_old"
  artifacts:
    paths:
      - public
