image: node:10.6.0

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
